services:
  app:
    container_name: web
    image: ${DOCKER_IMAGE}
    ports:
      - "3000:3000"
    restart: unless-stopped

    extra_hosts:
      - "host.docker.internal:host-gateway"

    env_file:
      - .env.docker

    environment:
      NODE_ENV: ${NODE_ENV}
      API_URL: ${API_URL}
      REDIS_URL: ${REDIS_URL}

volumes:
  redis_data:
