services:
  app:
    container_name: web

    image: ghcr.io/smoliarov/smoliarov-website:latest

    expose:
      - "3000"

    restart: unless-stopped

    env_file:
      - .env.docker

  nginx:
    image: nginx:alpine
    container_name: web-nginx

    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - app

    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro

      - /etc/letsencrypt:/etc/letsencrypt:ro

      - nginx-cache:/var/cache/nginx

    restart: unless-stopped

volumes:
  nginx-cache:
