services:
  app:
    container_name: web
    image: ghcr.io/lilscottypippen/smoliarov.site-v2
    ports:
      - "3000:3000"
    restart: unless-stopped

    extra_hosts:
      - "host.docker.internal:host-gateway"

    env_file:
      - .env.docker

volumes:
  redis_data:
